@server = https://ec3wiliansservice.onrender.com
#@api = {{server}}/api/ec3

################ Categorias: ################
GET {{server}}/categorias
################
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Instrumentos de cuerda"}
################ Instrumentos: ################
GET {{server}}/instrumentos
################
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Guitarra", "categoria": "http://localhost/categorias/1"
GET {{server}}/instrumentos/1/categoria
#
GET {{server}}/instrumentos?sort=nombre,desc